---
#dockerhub_version: "{{ lookup('file', playbook_dir + '/../VERSION') }}"
dockerhub_version: "19.2.0"

awx_image: "awx"
redis_image: "redis"

postgresql_version: "12"
postgresql_image: "postgres:{{postgresql_version}}"

compose_start_containers: true
upgrade_postgres: false
