version: '2'
services:

  web:
    image: quay.io/ansible/awx:19.2.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "8888:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "awxcompose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "awxcompose/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: quay.io/ansible/awx:19.2.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "awxcompose/redis_socket:/var/run/redis/:rw"
    environment:
      AWX_SKIP_MIGRATIONS: "1"
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "awxcompose/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "awxcompose/redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:12
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - "~/.awx/pgdocker/12/data/:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      http_proxy: 
      https_proxy: 
      no_proxy: 


volumes:
  awxcompose
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
